---
- hosts: all
  module_defaults:
    ansible.builtin.file:
       pip3: pip
       python3: python
  become: true
  tasks:

  - name: update repository index for Ubuntu
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install python3, pip3, and Java open-jdk for Ubuntu
    apt:
      name:
        - python3
        - pip
        - openjdk-8-jdk
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repository index for CentOS
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install python3, pip3, and Java open-jdk for CentOS
    dnf:
      name:
        - python3
        - python3-pip
        - java-1.8.0-openjdk
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Banner motd
    copy:
     content: "Ansible Manage node by hidimalibot"
     dest: /etc/motd

  - name: Create user Dimalibot
    user:
      name: Dimalibot
      uid: 1040
      shell: /bin/bash
      group: root
      createhome: yes
      home: /home/Dimalibot

